version: '3'
services:
  db:
    image: postgres:latest
    networks:
      - readback-network

  redis:
    image: redis:latest
    networks:
      - readback-network

  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rake db:migrate && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/app
    ports:
      - '3000:3000'
    depends_on:
      - db
      - redis
    networks:
      - readback-network
    environment:
      - REDIS_URL=redis://redis:6379/0

  sidekiq:
    build: .
    command: bundle exec sidekiq
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
    networks:
      - readback-network

  cable:
    build: .
    depends_on:
      - 'redis'
    command: puma -p 28080 cable/config.ru
    ports:
      - '28080:28080'
    volumes:
      - .:/app
    networks:
      - readback-network

networks:
  readback-network:
    driver: bridge
